### ISSUE TITLE
Get restaurant link is not working

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/full-stack-project#199]
I can't seem to be able to get my meals to display when I click on restaurant links. There's an issue with my requires. I have a get meal function and get restaurant function in 2 different files.

**Comment by RealWeeks** [comment]
what have you done so far to correct the error?

**Comment by Knguyen21** [comment]
I did many things, such as degugger, console.log, changing my files around, and changing my code.

**Comment by RealWeeks** [comment]
So in this there are 2 errors.
1. Getting meals to display when restaurant link is clicked
2. Fixing requires / exports.

Start with one issue, and dial in on that to get it working.  Ask more questions about a singular issue.

**Comment by jrhorn424** [comment]
> I did many things, such as degugger, console.log, changing my files around, and changing my code.

In addition to Jason's suggestions, you should also note every command you run and every piece of output you get, as well as what you were expecting to see. If you paste these, we can provide help faster. If we have to ask for more detail, it frustrates both you and us since it takes longer to answer.
- http://stackoverflow.com/help/how-to-ask
- https://codingkilledthecat.wordpress.com/2012/06/26/how-to-ask-for-programming-help/

**Comment by Knguyen21** [comment]
I don't know where to put my click handler to display the restaurant's meals when I click on the restaurant's name, which is generated from a GET AJAX request and displayed using handlebars in a bootstrap dropdown-menu .

**Comment by RealWeeks** [comment]
When the document loads it's usually good to register the click.

**Comment by RealWeeks** [comment]
When you click the restaurants name it sounds like you want to do something else. What is it your trying to do?

**Comment by jrhorn424** [comment]
@J-Weeks I read @Knguyen21's previous comment like this (it took a few re-reads to piece this together, so I might be mistaken):
1. The restaurant dropdown is populated with a GET request. (maybe doc ready?)
2. There should be a handler on each `<option>` in the list. When a restaurant is clicked, the main content area should display the meals associated with that restaurant.

The click handler will be tricky, since Handlebars is used to populate the dropdown options.

**Comment by Knguyen21** [comment]
Yes Jeff. After a few attempts, I'm able to display the meals associated with that restaurant that is being clicked when I hardcoded the restaurant ID in my ajax request URL. However, I'm having a hard time getting the restaurant ID to be put in a variable so I can concatenate in my URL
