### ISSUE TITLE
Need to rollback migration

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#401]
Can I get instructions on rolling back a migration? 
I created a migration using scaffold, and decided I didn't need it. I tried to remove it. I used the drop table command. 
Then I decided I did need the table after all, so I created it again. I had to use --force to get it though. 
I decided to stop before I did any more damage.

**Comment by berziiii** [comment]
You may not need a rollback. Try removing first.

In order to remove a migration, you need to run `bundle exec rails d migration <ExactNameOfMigration>`. This will find and remove. Once that is done, check to make sure the migration file is gone from the `migrate` file and then run `bundle exec rake db:nuke_pave`. Then check the schema and DB to ensure it's structured appropriately.

**Comment by rosmith76** [comment]
What about the remove table migration file I have?

**Comment by rosmith76** [comment]
I did the actions above for my last two migration files. The schema looks fine, but I don't have a migration file for my latest table

**Comment by berziiii** [comment]
that is the name of the migration that you will be removing.

**Comment by berziiii** [comment]
What migration do you want to remove?

**Comment by rosmith76** [comment]
Solution: recreated migration with migration command then nuke pave.
