### ISSUE TITLE
Does this mean my data isn't "user owned"?

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#461]
I can see this in my console. Does it mean my data isn't "user owned"? See bottom right-hand corner, where I see credentials. 
![screen shot 2016-10-11 at 5 15 46 pm](https://cloud.githubusercontent.com/assets/14143334/19288986/9b607ffe-8fd6-11e6-9590-2a21ef46f6c2.png)

**Comment by julie1013** [comment]
This too:
![screen shot 2016-10-11 at 5 18 28 pm](https://cloud.githubusercontent.com/assets/14143334/19289026/bf9429ac-8fd6-11e6-885c-1aefa34f5816.png)

**Comment by jrhorn424** [comment]
No, "user-owned data" doesn't have anything to do with the sign-in request. User-owned data isn't implement if I have an account on your API and I can do the following (from curl, or any other client):
1. CREATE something as if I were you
2. UPDATE something you previously created
3. DELETE something you previously created.

**Comment by julie1013** [comment]
Ok so is what I'm talking about something that involves a level of security we haven't covered yet?

**Comment by jrhorn424** [comment]
> Ok so is what I'm talking about something that involves a level of security we haven't covered yet?

You mean the screenshot with the password in it? The browser has to be able to see your password, otherwise it couldn't send it to the server.

Ideally, we'd be using `https` which means your browser would still see the data in plain text, but it would be encrypted before being sent over the network.

When you deploy, you will be using `https`. But, you'll still be able to see passwords in the browser. That's normal.

**Comment by julie1013** [comment]
Same with the ID?

**Comment by jrhorn424** [comment]
I'm not sure why the ID is there, but I'm not concerned about it. It actually looks like a response from your server even though you're looking at "Preview" on the request.

You need the user ID to sign out anyway, so it has to be available in the browser.

**Comment by julie1013** [comment]
Huh interesting. A friend of mine seemed to be worried that this meant it would be easy enough for someone to plug in someone else's id and manipulate their data.

**Comment by jrhorn424** [comment]
> A friend of mine seemed to be worried that this meant it would be easy enough for someone to plug in someone else's id and manipulate their data.

Not if you use `current_user`. If you look over the past issues we've discussed `current_user` in, I believe you'll see that I suggest using `current_user` instead of using queries like `User.find(params[:user_id]).books` precisely for that reason.

`current_user` determines `user_id` passed on the token that was sent with the request. That's why it is safe and doing manual user lookups (`User.find` or `QualifiedBooks.where(user: params[:user_id)`) isn't.

**Comment by bboodman** [comment]
Hi, I'm Brian, the friend Julie mentioned.

The specific concern I had was that Julie was sending the user id as an explicit form parameter.  So, either she was correctly using `current_user`, in which case the extra argument was useless, or she was using the id being posted, in which case it's a security hole.  Either way, the user id should be accessed via the authentication token (using `currentuser`, as you said), not sent explicitly as an additional form parameter.

**Comment by jrhorn424** [comment]
> Either way, the user id should be accessed via the authentication token (using currentuser, as you said), not sent explicitly as an additional form parameter.

I agree, and `user_id` should **not** be whitelisted in strong parameters.

**Comment by jrhorn424** [comment]
Thanks for joining the discussion, @bboodman.

**Comment by jrhorn424** [comment]
@bboodman Seems like you've deleted your comment. I want you to know I was sincere. You're welcome here. Thanks for pointing out the redundancy in including `user_id` when `current_user` is utilized.

**Comment by julie1013** [comment]
OK, looks like my question was answered. Thanks! :)
