### ISSUE TITLE
Attempting to redeploy

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/full-stack-project#463]
Hello!

I fixed a bug in gh-pages and pushed it. However, I am getting an error in my deployed client version:

```
vendor.bundle.js:9285 Mixed Content: The page at 'https://viohlet.github.io/project2-client/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/sign-up'. This request has been blocked; the content must be served over HTTPS.
```

Deployed browser: https://viohlet.github.io/project2-client/
https://github.com/viohlet/project2-client
Deployed api:  https://fathomless-ridge-48028.herokuapp.com/
https://github.com/viohlet/project2-api/tree/master/config

I changed my app.js file in my client to show the heroku link, but have the issue still. 

I also changed the api's client_origin link to:

```
origins ENV['CLIENT_ORIGIN'] || 'https://viohlet.github.io'
```

even though what worked before for me was:

```
 origins ENV['CLIENT_ORIGIN'] || 'http://localhost:3000'
```

I tried with both but none of them work.

Looking forward to hear your feedback! Thanks,
Violeta

**Comment by payne-chris-r** [comment]
It's telling you the error. `...insecure XMLHttpRequest endpoint 'http://localhost:3000/sign-up'. This request has been blocked; the content must be served over HTTPS`

**Comment by jrhorn424** [comment]
To future developers reading this issue, and current developers who may have done this: **never** change this line:

> `origins ENV['CLIENT_ORIGIN'] || 'http://localhost:3000'`

After checking that this was correct in the API code and that the appropriate environment variable was set on Heroku, we reproduced the problem.

As @payne-chris-r noted above, the problem was that the client was still set to talk to the local API instead of Heroku.

@viohlet had indeed set the correct URL in her app, but when deploying, and not run `grunt build` and as a result, `bundle.js` still had the old code in it.

@viohlet please add any notes if you'd like and then close if appropriate. Thanks!

**Comment by viohlet** [comment]
Apologies for the delay. That was indeed the problem, Jeff. Won't be forgetting to run grunt build at deployment for a long time. Thank you!
