### ISSUE TITLE
Ignore Empty Fields

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/full-stack-project#530]
Wondering if anyone has any ideas on this?  I have a form that updates a few fields on a record .  I currently present the User with a form presenting all updatable fields.  The conundrum is that if the user doesn't enter data in one of the fields it will populate the db with null value - thus overwriting valid data.  At this hour I don't want to redo things and have been researching a way to filter null fields at the model level.  So far...nada.

**Comment by raq929** [comment]
Well, you have to make a choice based on your app, and what you want it to do.
Often developers will take the data they have about the object and pre-populate the fields, so that a user would have to actively delete the value if they wanted to change it to null. Alternatively, you could have your front or back end go through, search for null values, and ignore those updates. However, that makes it impossible for a user to set a value to null if they want to. 
I think the right choice is probably pre-populating your fields with the object's existing data.

**Comment by rickdean** [comment]
Good idea.  I considered that and will look into it.  Thanks again as always!
