### ISSUE TITLE
scaffolding: a debate

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#591]
Some are of the opinion that we should not scaffold new models. Why would we not want to?

**Comment by raq929** [comment]
Scaffolding has it's pros and cons. It can be a quick way to get your table up and running. You do have to remember to take out some things, like the `location:` bit, that will get in your way. 

Personally, I like to go from a working example (like the `examples_controller`. I know it works, it has curl requests already written that I just change the names on, etc. (I do always use `rails generate` to create models, controllers, and serializers.) Using a working example, I can add my methods one at a time, using the name of my model instead of `Example`, and I can be sure that it'll work or that I made a mistake. 

In the end, it's up to you whether you scaffold or not. Remember that ownership is required for this project, so you'll need to change at least one controller to have user-owned data.

**Comment by raq929** [comment]
@jrhorn424 do you have an opinion here?

**Comment by MicFin** [comment]
I don't mind scaffolding.  Especially in the beginning when you are building mostly CRUD resources.  I think the downsides of scaffolding are that it 

1.  Adds more than you need sometimes and in the beginning you don't know what is safe to remove. 
2.  If all you do is scaffold then Rails is creating all the files for you so when you CAN'T scaffold, you will potentially not know where all the files go and what they should contain.

As seen below, developers will always have opinions so just use what you are comfortable with and while you are learning, try different things.  Scaffold one resource, but then build another resource from scratch.  *The process of doing both is more valuable than figuring out which is better right now.*
- [StackOverflow Debate](https://stackoverflow.com/questions/6735468/why-do-ruby-on-rails-professionals-not-use-scaffolding)
- [StackExchange Debate](https://softwareengineering.stackexchange.com/questions/75011/do-experienced-ruby-on-rails-developers-use-scaffolding)

**Comment by jrhorn424** [comment]
> Some are of the opinion that we should not scaffold new models.

It's a preference to avoid scaffolding. It's also wrong. 😉 

I like not making silly typos.
