### ISSUE TITLE
Handle Bars

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/full-stack-project#618]
I am generating a div and update button in modal format for each element in the array like object. I have dedicated a class called "submit-update" for my click event handler to get the data in the form to send a patch request to api server. However, when I click the submit button it closes the model without even sending a request. I am not sure what is the problem.

<=== Handle Bar ===>
```
{{#each accounts as |account|}}


   <div data-id="{{account.id}}">
     <p>{{account.web_name}}</p>
     <p>{{account.password_hint}}</p>

     <!-- Button trigger modal -->
     <button type="button" class="btn btn-default" data-toggle="modal" data-target="#{{account.id}}">
       Launch demo modal
     </button>

     <!-- Modal -->
     <div class="modal fade" id="{{account.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
       <div class="modal-dialog" role="document">
         <div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="myModalLabel">Modal title</h4>
           </div>
           <div class="modal-body">
             <form class="submit-update">
               <h1 >Update!</h1>
                 <input type="text" name="account[web_name]" value="{{account.web_name}}">
                 <input type="text" name="account[password_hint]" value="{{account.password_hint}}">
                 <input type="submit" name="submit">
             </form>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           </div>
         </div>
       </div>
     </div>


     <button type="button" name="button" class="btn btn-default remove">Remove</button>
   </div>

{{/each}}
```

<===Click event===>
```
  $('.submit-update').on('submit', onPatchAccount);
```

<==Events====>
```
const onPatchAccount = function(event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  api.patch(data)
    .then(ui.onPatchSuccess)
    .catch(ui.onError);
};

```

<===Api===>

const patch = function(data){
  return $.ajax({
    url: config.apiOrigin + '/accounts/' + `${store.account.id}`,
    method: "PATCH",
    headers:{
      Authorization:`Token token=${store.user.token}`
    },
    data,
  });
};

**Comment by MicFin** [comment]
Please style your code using https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

So instead of 

```
<==Events====>
const onPatchAccount = function(event){
  event.preventDefault();
 let data = getFormFields(event.target);
 console.log(data);
  api.patch(data)
    .then(ui.onPatchSuccess)
    .catch(ui.onError);
};
```

We can see


```js
// events.js

const onPatchAccount = function(event){
  event.preventDefault();
  let data = getFormFields(event.target);
  console.log(data);
  api.patch(data)
    .then(ui.onPatchSuccess)
    .catch(ui.onError);
};
```

**Comment by raq929** [comment]
I would try following the steps laid out in #529 to be sure that your click handler is set correctly. I suspect it isn't, and therefore your page is refreshing instead of the click handler firing. (The instructions there are for starting from scratch; I'd comment out your code in the handler and then add it back in step by step.)

As a side note, you should avoid using just numbers as ids for your forms - this may result in more than one element having the same id, which could cause major problems.

**Comment by raq929** [comment]
AH. So, your click handler is set on `.submit-update`. But when your click handler is set, that class does not exist yet. So you have no click handler. 
Which is great, because it could mean the rest of your code is perfect. (I would still follow the steps in the issue I linked to above.)
In our handlebars repo, it talks about how to set click handlers on elements that don't exist yet. The very very bottom of the jQuery documentation about `.on()` might also point you in the right direction. http://api.jquery.com/on/
(Why they put the useful stuff all the way at the end is beyond me.)

**Comment by wilsonkaya** [comment]
Thank u very much Rachel. It was a great help. I overcome the issue by setting the event on a parent that appears on page load. 

```
  $('#content').on('click','.remove' ,onDeleteAccount);
```
