### ISSUE TITLE
How to display movie title

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#632]
I think this might be a simple issue but I can't seem to figure it out.

I want to display a movie title on my webpage instead of the movie id.
When I click on my favorites button it only displays the movie id. 
But the json returning from favorites only has movie id as a parameter. 
Does this mean I need to insert a column into my favorites table for move_title? 
So that I can interpolate the string and get the title from it?

I know how to use a 3rd party api to get movie information out so does that mean I need to set up a way to favorite those movies and then get the titles from that?

**Comment by raq929** [comment]
You can use the rails serializer to give you the data you want. If you add the relationship to the serializer (similarly to the way you did with the model, it should give you all of the movie data instead of just the id).

**Comment by ggabrakadabra** [comment]
But if I want to use the 3rd party api and use the movie titles and ids from that is there a way to pull can I pull that data out and store into my database?

**Comment by raq929** [comment]
Ah. Possibly, but that may not be the best option. It's probably best to just make a get request  in that case to have the most up-to-date data from the third party API. Otherwise you end up with 'dirty data': your data may be out of sync with the third party, and you're storing it in two places, unnecessarily. I think getting the id and then making a GET request to the third party API is probably your best bet.

fwiw, I would concentrate on getting requirements met for now, and add the third party API in afterwards as a stretch goal.
