### ISSUE TITLE
Bubbling and screen gets dark

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/full-stack-project#634]
When I do patch request from by browser template I receive 200 ok from my api, after having a visual change in my html my screen gets grey and everything becomes blocked. I have even tried body for stop bubbling, it didn't work. Actually I tired every possible parent.

<==Event Listener ==>
```
  $('#content').on('submit', '.new-dest', onPatchAccount);
```

<== Handle bars ==>
```
{{#each accounts as |account|}}


   <div data-id="{{account.id}}" class="new-dest">
     <p>{{account.web_name}}</p>
     <p>{{account.password_hint}}</p>

     <!-- Button trigger modal -->
     <button type="button" class="btn btn-default" data-toggle="modal" data-target="#mod{{account.id}}">
       Update!
     </button>

     <!-- Modal -->
     <div class="modal fade kapat" id="mod{{account.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
       <div class="modal-dialog" role="document">
         <div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="myModalLabel">Update!</h4>
           </div>
           <div class="modal-body">
             <form class="submit-update" data-id="{{account.id}}">
                 <input type="text" name="account[web_name]" value="{{account.web_name}}" class="clean-update">
                 <input type="text" name="account[password_hint]" value="{{account.password_hint}}" class="clean-update">
                 <input type="submit" name="submit">
             </form>
             <div class="warning-update-data">

             </div>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           </div>
         </div>
       </div>
     </div>


     <button type="button" name="button" class="btn btn-default remove" data-id="{{account.id}}">Remove</button>
   </div>

{{/each}}
```

<== ui ===>
```
const onPatchSuccess = (data, accountId) => {
  $(".warning-update-data").text("Succesfull !");
  setTimeout(function() {$('.kapat').modal('hide');}, 1300);
  setTimeout(function() {$('.warning-update-data').text("");}, 1300);
  let showBooksHtml = updateAccount({ account: data.account});
  // setTimeout(function() {$('[data-id ='+ accountId +']').html(showBooksHtml);}, 1300);
$('[data-id ='+ accountId +']').html(showBooksHtml);

};
```

<==HTML==>
```
<div id="show">
  <button id="getBooksButton" class="btn btn-default">Get Accounts</button>
  <div id="content">
  </div>
</div>

```

**Comment by raq929** [comment]
Why are you setting a timeout instead of just hiding the modal?
This sounds like an issue with bootstrap not hiding the modal correctly. 
I'll take another look in the morning.

I suspect the click handler, `$('#content').on('submit', '.new-dest', onPatchAccount);` should be set on the form, not on the parent div `.new-dest`.

**Comment by wilsonkaya** [comment]
My modals are working well when I don't call the code below patch works perfectly but could not change html. On the other hand, ```.new-dest``` was set on form. I have changed to parent to try if it would make any difference. 

```
  let showBooksHtml = updateAccount({ account: data.account});
  // setTimeout(function() {$('[data-id ='+ accountId +']').html(showBooksHtml);}, 1300);
$('[data-id ='+ accountId +']').html(showBooksHtml);
```

**Comment by raq929** [comment]
Ok. Let's keep `.new-dest` on the form.
So, without this code, your patch works? 
I'm confused about what you're trying to do here on the last line:
`$('[data-id ='+ accountId +']').html(showBooksHtml);`
What element are you trying to target?

Is this to show a list of books, or just one book? Because the handlebars file you posted is going to try to display a list. You'll need a different template to show just one account.

**Comment by wilsonkaya** [comment]
Sorry, I have sent the wrong handlebars. My update handle bar only creates one item and over writes a certain file according to data-id. In my event.js I get attribute the specific data-id of the element  and  assing it to ```accountId```

```
const onPatchAccount = function(event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  let accountId = event.target.getAttribute('data-id');
  // console.log(data,accountId);
  api.patch(data, accountId)
    .then(ui.onPatchSuccess(data,accountId))
    .catch(ui.onError);
};
```

```

<div data-id="{{account.id}}">
  <p>{{account.web_name}}</p>
  <p>{{account.password_hint}}</p>


  <!-- Button trigger modal -->
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#mod{{account.id}}">
    Update!
  </button>

  <!-- Modal -->
  <div class="modal fade" id="mod{{account.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Update!</h4>
        </div>
        <div class="modal-body">
          <form class="submit-update" data-id="{{account.id}}">
            <input type="text" name="account[web_name]" value="{{account.web_name}}" class="clean-update">
            <input type="text" name="account[password_hint]" value="{{account.password_hint}}" class="clean-update">
            <input type="submit" name="submit">
          </form>
          <div class="warning-update-data">

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


  <button type="button" name="button" class="btn btn-default remove" data-id="{{account.id}}">Remove</button>
</div>
```

**Comment by wilsonkaya** [comment]
I can see that patch is working and it is also changing the html but screen suddenly becomes grey and everything gets blocked.

**Comment by raq929** [comment]
Yeah, that's a thing that happens when bootstrap isn't fully closing the modal. 
I'm unclear on what html you're changing. It seems like you might be overwriting the html with your modal in it, in which case, that's likely your problem. When Bootstrap opens a modal, it greys out the screen behind the modal in the way you're describing. When the modal is closed, it both hides the modal and removes the greyness. If you just overwrite the modal without closing it, then the grey will stay there.

Another problem you may be having. Right now, you're targeting things based on their data-id. Based on this form, you're targeting at least two things that way. I think that's likely not what you want to do. 
I would `console.log($('[data-id ='+ accountId +']'))` to take a look at what exactly you're targeting and be sure that it's what you want. (I also think there's easier ways to target it than this but if it works, whatever.)

There are a few options here.
1) Don't use a modal. Just hide and show a regular form.
2) Close the modal on form submit. Be sure that works correctly (without trying to do anything else.) Then add your other functionality back in. 

OK, I could only think of two options. But I'm sure there's more ways to get around this problem. 😄

**Comment by wilsonkaya** [comment]
I can't understand why using data-id will be problem. Each of them have different id. How can I address two different thing by using data-id ?

**Comment by wilsonkaya** [comment]
Thank you very much I have handle my problem by lunching the code after the modal closes 

```
setTimeout(function() {$('[data-id ='+ accountId +']').replaceWith(showBooksHtml);}, 1475);
```

**Comment by jrhorn424** [comment]
http://getbootstrap.com/javascript/#modals-methods

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/full-stack-project/issues/636#issuecomment-281119805
