### ISSUE TITLE
Appending issue 

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/full-stack-project#642]
On success of get, application is appending data that comes from handle bars and as you can guess when I make the request it repeat the data. I have tried ```if( $('#content').is(':empty') ) {```
to check if the div is empt or not but it didn't work. I even tried checking innerHTML of the div but it doesn't work. 

```
const onSuccess = (data) => {
  let showBooksHtml = showBooksTemplate({ accounts: data.accounts });
  $('#content').append(showBooksHtml);
};
```
```
<div id="show">
  <button id="getBooksButton" class="btn btn-default">Get Accounts</button>
  <div id="content" class="content">
  </div>
</div>
```

**Comment by raq929** [comment]
Looks like you're mixing up JS and Ruby here: `:empty` doesn't mean anything in js.
If I were doing this, I'd probably use the jQuery getter `.text()`, and check to see if it's the empty string.

However, I think you can simplify this a lot by not using `append()`. If you use `.html()` instead, you avoid having to check for content at all; you'll just replace the whole list every time. This is also a better option because it will provide the most up to date data if something on your list is updated. Your strategy above might not.

**Comment by wilsonkaya** [comment]
Thank you very. It worked perfectly.
