### ISSUE TITLE
request one on one

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#653]
I requested a one on one a few days back in issue 598 & 635.  the specific issue was addressed, but I was also looking for guidance on my project.

**Comment by raq929** [comment]
Please let us know what you want guidance on, and what you have tried, and any appropriate code.

**Comment by Soboscott** [comment]
I am working on the back end and have questions on testing and since I had such a hard time with the setup I would like to have second eyes on it before I continue.

**Comment by raq929** [comment]
Testing what? Second eyes on what? We can't look over your entire back end, so I'd like you to figure out what we can do that will give you the ability to reassure yourself about the rest of the back end. I also want you to be more specific because learning to articulate problems is an important part of being an effective developer. 

Also, please answer the question about what you've tried. If you haven't tried anything, I'm curious as to why. Experimenting is an important part of the process. 

Thanks!

**Comment by jrhorn424** [comment]
@raq929 Sorry for the miscommunication. I didn't inform you that Scott had already requested a 1on1 through Slack and I asked him to post here.

**Comment by jrhorn424** [comment]
Related: #598 and #635

**Comment by jrhorn424** [comment]
@Soboscott Is it correct to say you're looking for guidance on what to work on next?

If that's the case, I'll need to see your planning materials (ERD, wireframes, user stories) as well as a todo list or an outline of what you intended to work on and when. For anything completed, we'll also discuss how you tested (manually, and with `curl`) the code to ensure it works as expected.

**Comment by Soboscott** [comment]
I've got all that plus.

**Comment by jrhorn424** [comment]
@Soboscott and I took Ockham's razor to his entity relationships, focusing on the simplest structure that accomplished what he wanted in his app.

We also developed a check-list to finish his API.
