### ISSUE TITLE
finish 1 on 1 with mike

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#711]
looking at the api curl request

**Comment by Soboscott** [comment]
I am still getting the 500 error:
this is what I ran after doing the git add,commit,push, heroku master push.
I ran this with and without "" around the ID=
I have a user id 1 and a trail id 2
do I need to take out the userID out of the script because it is not called for in the controller?
```
$ COMMENT="too long" TRAIL_ID="2" USER_ID="1" TOKEN="BAhJIiU0MjU2MDZkYzc3MDg3MzI5ZDk0ODQ0OTFiNjU4ZjBkNQY6BkVG--f373f917f5c27afd594872da98a096304c491234" sh scripts/reviews/create.sh
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Wed, 01 Mar 2017 21:23:56 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
X-Request-Id: f73971c2-85ab-4c1c-ab08-b5a03625b6ff
X-Runtime: 0.014435
Vary: Origin
Content-Length: 46
Via: 1.1 vegur

{"status":500,"error":"Internal Server Error"}
~/wdi/projects/trail-rater (master)
$ 
```
I checked my controller:

```

# frozen_string_literal: true
class ReviewsController < OpenReadController
  before_action :set_review, only: [:destroy]

  # GET /reviews
  def index
    @reviews = Review.all

    render json: @reviews
  end

  # POST /reviews
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created, location: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
  # DELETE /reviews/1

  def destroy
    @review.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:comments, :trail_id)
  end
end
```
and my script is:

```
# !/bin/bash
API="${API_ORIGIN:-https://trail-rater.herokuapp.com/}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "review": {
      "comments": "'"${COMMENT}"'",
      "trail_id": "'"${TRAIL_ID}"'",
      "user_id": "'"${USER_ID}"'"
    }
  }'

echo
```

**Comment by Soboscott** [comment]
I commented out the user id and got : 
```$ COMMENT="too long" TRAIL_ID="2" TOKEN="BAhJIiU0MjU2MDZkYzc3MDg3MzI5ZDk0ODQ0OTFiNjU4ZjBkNQY6BkVG--f373f917f5c27afd594872da98a096304c491234" sh scripts/reviews/create.sh
HTTP/1.1 400 Bad Request
Server: Cowboy
Date: Wed, 01 Mar 2017 21:36:59 GMT
Connection: keep-alive
Content-Type: text/html; charset=utf-8
X-Request-Id: 8a66b0de-1e23-49e0-8ffb-d7f55d5358b3
X-Runtime: 0.006364
Vary: Origin
Content-Length: 0
Via: 1.1 vegur

```

**Comment by MicFin** [comment]
Commenting out the `user_id` from your curl script was a good idea since your `review_params` does not allow a `user_id`.

```rb
  def review_params
    params.require(:review).permit(:comments, :trail_id)
  end
```

I looked up `400 bad request` and [found](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error)
> **400 Bad Request**
> The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, too large size, invalid request message framing, or deceptive request routing)

The phrase `malformed request syntax` led me to check the syntax in your curl script.  
You mentioned that you commented out the `user_id` so I imagine it looks like below:

```
# !/bin/bash
API="${API_ORIGIN:-https://trail-rater.herokuapp.com/}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "review": {
      "comments": "'"${COMMENT}"'",
      "trail_id": "'"${TRAIL_ID}"'",
      // "user_id": "'"${USER_ID}"'"
    }
  }'

echo
```

I always like to reference a curl script from the solution branch of a lesson in class like the [rails-api-bdd ](https://github.com/ga-wdi-boston/rails-api-bdd/blob/solution/scripts/create-example.sh) lesson.

```
# !/bin/bash
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/examples"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "example": {
      "text": "'"${TEXT}"'"
    }
  }'

echo
```

It looks like the comment should not be in there.  There may be other issues in the syntax, please look carefully.

In your terminal command, we can send numbers as numbers and not strings .
```
COMMENT="too long" TRAIL_ID=2 TOKEN="BAhJIiU0MjU2MDZkYzc3MDg3MzI5ZDk0ODQ0OTFiNjU4ZjBkNQY6BkVG--f373f917f5c27afd594872da98a096304c491234" sh scripts/reviews/create.sh
```

Try naming your issues more targeted towards the problem so other consultants and developers can potentially help as well.  For this issue, I might have named it `Server error 500 for curl POST resource`.

Also, if you work in your `development` environment and run your server locally then you can use `binding.pry` in your controller to debug when you see server errors like `400`.  It is best to debug our applications in `development` and then `push` to heroku once we have solved a bug.  You will need to change the URL in curl request to your `localhost` to debug locally.

**Comment by Soboscott** [comment]
I deleted the line with the user_ID, but I'm still getting a 400 error.
I'm going to try some things and look more on the interweb to see if I can resolve this.
