### ISSUE TITLE
Blocking blank form inputs

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/full-stack-project#852]
My Create and update functionality both use form fields to determine what will be passed through to the server. How can I stop a user from passing in an empty string? My guess is that it is in the controller for movie, but I am not sure what the syntax for blocking invalid input is.

**Comment by MicFin** [comment]
I would recommend using both HTML validation and javascript/jQuery to validate the form before ever making the AJAX call.  

Here are a few examples to look at.

HTML validation
- https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation
- http://www.the-art-of-web.com/html/html5-form-validation/
- https://www.sitepoint.com/html5-form-validation/

Javascript/jQuery validation
- You could write a function that checks if the result of `getFormFields` has empty strings and if it does then instead of calling the API, it displays a message to the user to complete the form.
- https://www.tutorialspoint.com/javascript/javascript_form_validations.htm

**Comment by d00medman** [comment]
I ended up going the route of working with the results of getFormFields. Now, I need to find some way to check a string to see if it has any alphabetical characters in it. How would I go about doing something like this in javascript?

**Comment by tvcrawley** [comment]
[LMGTFY](http://lmgtfy.com/?q=javascript+check+string+contains+alphanumeric)

**Comment by d00medman** [comment]
Solved the problem. The following code ensures that inputs of a blank string are blocked

```js
if (/[a-z]/.test(input.toLowerCase()) === false)
```
