### ISSUE TITLE
Issue parsing with getFormFields

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/full-stack-project#892]
So, I'm using getFormFields to capture a form containing a `textarea` with a code snippet. A code snippet is loosely defined as a block of multi-line text.

I encountered a critical failure when the contents of the `textarea` was a hello world script in Objective C. It didn't need to be that, just happened to be the snippet I pasted in.

```
#include <stdio.h>
#include <objpak.h>
int main(int argc,char **argv)
{
    id set = [Set new];
    argv++;while (--argc) [set add:[String str:*argv++]];
    [set do:{ :each | printf("hello, %s!\n",[each str]); }];
    return 0;
}
```
I was able to identify the issue in the `addNestedValue(target, name, e.value)` , specifically the line:
```
 value = decodeURIComponent(value)
```
Something in the snippet was returning an invalid URI.

My short term work around was commenting out the decodeURIComponent(value) line on my code.

**Comment by MicFin** [comment]
Great job identifying where the bug was.
% is a special character to `decodeURIComponent`.  Single % followed by a space breaks the logic of `decodeURIComponent()` function as it expects two-digit data-value followed right after %, for example `%20`.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent

Potentially, the `getFormFields` function has a bug when handling `TEXTAREA` input types that include a `%`.

How could you further test that?

What part of the `getFormFields` or `addNestedValue` method might you alter to handle that scenario?

**Comment by pjliddy** [comment]
I've checked the other input fields with values containing % signs and didn't get any problems.

I'm going to raise a semantic argument here, though. The validation for escaping characters in URLs for every type of input seems overly aggressive and beyond its expected scope.

There is an html input type of `url` for which that type of filtering is appropriate and expected. I'm not sure of the exact pattern causing the issue, but not every % used in a form input is intended to indicate a character code that needs escaping.

There are already different options in getFormFields for TEXT, and some other types, so could it be the right approach to keep the URL escaping for URL (and maybe email?) but not for generic text inputs?

I'm going to read up on decodeURIComponent tomorrow and see what else there is to learn.

**Comment by jrhorn424** [comment]
This is fascinating.

**Comment by jordanallain** [comment]
still looking for further feedback on this @pjliddy ?
