### ISSUE TITLE
Requirements clarification

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#924]
Quick question what exactly are the requirements for our front-end? Instructions are somewhat vague?

**Comment by danman01** [comment]
Which part do you need clarification on? This project involves building an API and a front-end that consumes your API using AJAX to complete the four CRUD actions. Apologies for re-posting what you've likely already read, but this will give us a starting place to clear up any confusion:

## Deliverables

- A working full-stack application, built by you, hosted somewhere on the internet.
- Two Github repos (one for your front-end and one for your back-end), with frequent commits dating back to the very beginning of the project. Each repo will need a README.md file with a link to the other repo. Your front-end repo's README should also have
- 
- An explanation of the what the app does and how it works, the approach taken in building it, and any unsolved problems that you hit.
- User stories written for your app.
- At least one wireframe (or a link to one) that you've created to plan out your app.
- A link to the live application.

## Your app must

- Have an API that is securely accessible by your browser app, built using frameworks covered in class.
- Create at least 4 RESTful routes for handling GET, POST, PUT/PATCH, and DELETE requests. Any actions which change data must be authenticated, and the data must be "owned" by the user performing the change.
- Utilize an ORM to create a database table structure and interact with data
- Use a front-end Javascript app to communicate with your API (both read and write) and render data that it receives in the browser.
- Have semantically clean HTML and CSS
- Be deployed online, so that it is accessible to the public
- Be linked in your pinned repositories on your GitHub profile page
##Your app must not

- Have any obvious user-facing errors
- Rely on refreshing the page for any functionality.

**Comment by ghost** [comment]
I guess I just ned a clarification on whether the specifics of our front-end actions are up to us

**Comment by danman01** [comment]
They are, as long as they meet the requirements of consuming your API and allowing users to perform actions in the described manner.

**Comment by ghost** [comment]
Thanks
