### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#926]
Trying to create a user in the database from the front end and get a 400 bad request error.  My api looks like
```const createUser = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/people',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data
  })
}```js

error reads ```POST http://localhost:4741/people 400 (Bad Request)```

**Comment by danman01** [comment]
What is in your `data`? 

If you look at your rails server, what output regarding the error do you see?

**Comment by ghost** [comment]
Its saying data is 
```
Object {"": Object, submit: "Sign up!"}
""
:
Object
credentials
:
Object
email
:
"g@gmail.com"
userid
:
"1"
```

**Comment by ghost** [comment]
It doesn't change the back-end, no error

**Comment by danman01** [comment]
How are you setting up the `data` variable, and what information do you actually want to send so that your Rails `create` route receives the correct data? What is Rails looking for, and what are you sending? Can you work with the `data` variable to have it contain the values and be structured in the way that your Rails route / controller wants?

**Comment by ghost** [comment]
Not sure what you're asking, sorry

**Comment by ghost** [comment]
Solved issue, was passing through wrong data, edited index.html, and fixed resulting server error
