### ISSUE TITLE
actions that can, but do not require, authentication of user

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#928]
I have an API GET call that return:
* some data for any user (does not need to be logged in)
* plus some additional user-specific data if the user is logged in.

A POST to the same URL requires user authentication.

I have chosen to create the controller as follows:
```
class MatrixController < ProtectedController
  skip_before_action :authenticate, only: :index
…
```
Thus, `update` will require authentication — great!
And `index` does not _require_ authentication — also great!

But... if user provides his token with `index`, how can I (a) get the token authentication, and (b) find out the corresponding `user_id`?

**Comment by EricLScace** [comment]
A search for `ActiveRecord ProtectedController methods` didn't yield much of any relevance. Is this a GA-custom class?

**Comment by danman01** [comment]
Yes, this is a GA controller, which inherits from the GA rails template ApplicationController, which holds the `set_current_user` and `authenticate` methods.

I would think about setting up `index` to do one thing if `current_user` is nil, and another thing if `current_user` is an actual user, meaning they successfully authenticated. Once you have `current_user`, you can retrieve the user data including the ID from that object.

**Comment by EricLScace** [comment]
I'm looking around in here Ruby on Rails Docs for appropriate methods: 
<ActionController::HttpAuthentication::Token::ControllerMethods>

**Comment by MicFin** [comment]
This should be helpful to review.  There is another method than `authenticate` that will set `current_user` for you that is inherited.
- Note the method it invokes after skipping `authenticate` https://git.generalassemb.ly/ga-wdi-boston/rails-api-template/blob/master/app/controllers/open_read_controller.rb
- Note that method exists due to inheriting from application_controller 
https://git.generalassemb.ly/ga-wdi-boston/rails-api-template/blob/master/app/controllers/application_controller.rb

**Comment by EricLScace** [comment]
OK, will dig into these this evening.

**Comment by EricLScace** [comment]
`before_action :set_current_user, only: :index` does the trick!
