### ISSUE TITLE
refactoring (some day…) long controllers

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/full-stack-project#937]
I have a long controller. It's got plenty of shorter private methods.

As a theoretical question:
* at least 2 logical constructs in the controller could be better represented as classes, with their own methods.
* is it a correct construction to place these classes in a different file... and do I need an `include` statement so that the controller knows where to find the classes and their methods?

Something like this would be so much cleaner than what I have now :-(

**Comment by danman01** [comment]
If you want to move methods into a Class or Module, and then include / require those files, that sometimes makes sense when refactoring, but sometimes it's not needed. Just because it's a long file doesn't necessarily mean the code shouldn't be there. 

Here's a good intro to refactoring patterns. It's talking about refactoring models, but could apply to controllers as well: http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/

Regarding how to use the external file, you can simply make a class file in the models folder, and that should be available to your controllers. If you create the class file in the lib folder, you will need to `require` that file unless the Rails config auto includes all files in the lib directory. For modules, you will need to `include` the module. More: https://www.benfranklinlabs.com/where-to-put-rails-modules/

As for the more correct place for these files, It's debatable. I say, if it is a class and deals with an ActiveRecord entity, the class should go in the models folder, otherwise it should go in the lib folder.

**Comment by EricLScace** [comment]
Maybe I'm doing this wrong. I have no code in my model other than the basic class definition and has_many. All my programmatic logic is in the controller.

If this isn't correct practice, it's too late to refactor for tomorrow. But I'll clean it up for v1.1

**Comment by danman01** [comment]
👍 it's debatable, fat controller vs fat model...as long as it makes sense to you and works, that's what is important for the MVP / V1

**Comment by EricLScace** [comment]
Thanks.
