### ISSUE TITLE
if my get all list is visible and then i use create function i am not able to use the created thing on my list

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/full-stack-project#938]
````
const onCreateCar = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  // debugger
  api.createCar(data)
    .then(ui.createCarSuccess)
    .catch(ui.createCarfailure)
}
````
api call
`````
const createCar = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/cars',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data
  })
    // .then(console.log)
    .then((response) => {
      console.log('ajax sucessful')
      store.carId = response.car.id
      return store
      // $("ul[data-id='" + data + "']").find('.rep').text(response.car.data)
    })
}

**Comment by danman01** [comment]
Are you saying that after you create a car, that newly created car is not shown in your list of all cars? So you need to somehow append the new car to the list, or refresh your list to grab all the cars?

**Comment by isharma-sharma** [comment]
yes if my list is open it will not show my car

**Comment by danman01** [comment]
Ok, so just because the car is created does not mean it automatically gets placed into the DOM or added to any list. You will manually need to either call your index sequence again to do a new AJAX request and get all cars (including the new one), and then update the UI appropriately, or simply append the newly created car to the DOM so that the user sees the new car. 

In your `.then(ui.createCarSuccess)` method, you can likely experiment with appending the car, or after this `.then`, chaining another promise that calls your api again for the `index` method.

**Comment by isharma-sharma** [comment]
i tried this but not working
```
const createCar = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/cars',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data
  })
    // .then(console.log)
    .then((response) => {
     
      $("ul[data-id='" + data + "']").find('.rep').text(response.car.data)
    })
}

**Comment by danman01** [comment]
Be careful of what you are returning, and think of when the best place to call your next function should be. Here's an in-depth read about promises. It'll take 20-30 minutes but is well worth it: https://developers.google.com/web/fundamentals/getting-started/primers/promises

I would advise either chaining after you call `ui.createCarSuccess` or simply do the updating of the UI within that function, as the `ui.createCarSuccess` is responsible for updating the UI. Think about responsibility of the various files and functions you have, and be careful about simply adding code to functions because that code needs to run. First think, is this the best place to run this code? Does it make sense that this code runs within this particular function? Is it named appropriately? These are refactoring steps, but getting into that habit of being critical of how your code is written is a good thing.

**Comment by isharma-sharma** [comment]
i tried this i can see things on my console but not my list
```
const createCar = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/cars',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data
  })
    // .then(console.log)
    .then((response) => {
      debugger
      console.log(data)
      $("ul[data-id='" + data + "']").text(response.car)
    })
}
and i also did this on my ui
```
const createCarSuccess = (data) => {
  console.log(data)
  console.log('created a car')
  $('input[type="text"]').text('')
  // $('#success').show()
  $('#error').hide()
  // $('#succmsg').text('your car is now added on the list')
  $('#crtnewcar').show()
  debugger
  event.onGetAllCars()
}  
but no change

**Comment by isharma-sharma** [comment]
i tried but the list is not updating at the time of create function sucess

**Comment by danman01** [comment]
By saying "no change" do you mean the car was not added to the list? Are you sure your javascript method to add the car to the list is working? Are you getting the console.logs you are using? Are you accessing the debugger in the place that you placed the debugger?

Think about this in the smallest possible steps...
1. Can you do something after you create a car? Console.log, debugger, etc?
2. Do you know how to change the dom after the car was created? Experiment in the debugger or with dummy code.
3. Can you change the dom so that the user is aware the car was created? Like a message to the user?
4. Can you add the new car to the dom?

**Comment by isharma-sharma** [comment]
i was thinking the same how can i add new element to the dom i was trying append method but that to didn't work

**Comment by isharma-sharma** [comment]
i m not able to do  create with my list open i tried appendchild() console say this is not  a function

**Comment by danman01** [comment]
How do you determine if something is a function, and how that function works / what arguments it takes, etc? Which documentation are you looking at while you are searching for the `append()` method?

**Comment by isharma-sharma** [comment]
i tried something else but the person will have to click the car list button to see his car because i was not getting what to do

and the documentation i was looking is 
https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

**Comment by danman01** [comment]
@isharma-sharma Please make a new issue if this one is resolved. Thanks!

**Comment by isharma-sharma** [comment]
have to create another handlebar template for resolving my problem

**Comment by danman01** [comment]
The new handlebar template for handling single-car create worked for solving this problem, correct?

**Comment by isharma-sharma** [comment]
yep i know i need to close the issue sorry i forget
